import type {
	CommunicationPreference,
	LeadSource,
	LeadStatus,
	LeadTypeGlobal,
} from "@/types/_dashboard/leads";

import { v4 as uuid } from "uuid";

export const leadStatus: LeadStatus[] = [
	"New Lead",
	"Contacted",
	"Qualified",
	"Proposal Sent",
	"Negotiation",
	"Closed Won",
	"Closed Lost",
	"Nurture",
] as const;

export const leadCommunicationMethods: CommunicationPreference[] = [
	"Email",
	"Phone",
	"Text",
	"Mail",
];
export const leadSources: LeadSource[] = [
	"Website",
	"Referral",
	"Cold Call",
	"Social Media",
	"Email Campaign",
	"Events",
	"Direct Mail",
	"Paid Ads",
	"Other",
];
export const staticMockLeadData: LeadTypeGlobal[] = [
	{
		id: uuid(),
		createdAt: "2023-09-10T09:00:00Z",
		updatedAt: "2023-09-10T10:00:00Z",
		firstName: "Candice",
		lastName: "Schiner",
		email: "testemail@gmail.com",
		phone: "(555) 123-4567",
		summary: "Discussed details about the 4-bedroom property.",
		status: "New Lead",
		source: "Website",
		properties: [
			{
				id: uuid(),
				address: {
					street: "123 Main St",
					city: "Springfield",
					state: "IL",
					zipCode: "62701",
					fullAddress: "123 Main St, Springfield, IL",
				},
				bedrooms: 4,
				bathrooms: 3,
				livingArea: 3200,
			},
		],
		activities: [],
		tags: [],
		followUpDate: "2023-09-12",
		lastContacted: "2023-09-10",
		metadata: {
			lastUpdate: "2023-09-10",
			address1: "123 Main St, Springfield, IL",
		},
	},
	{
		id: uuid(),
		createdAt: "2023-09-11T09:00:00Z",
		updatedAt: "2023-09-11T10:00:00Z",
		firstName: "John",
		lastName: "Doe",
		email: "testemail@gmail.com",
		phone: "(555) 234-5678",
		summary: "Interested in selling their 2-bedroom condo.",
		status: "Contacted",
		source: "Referral",
		properties: [
			{
				id: uuid(),
				address: {
					street: "456 Oak St",
					city: "Chicago",
					state: "IL",
					zipCode: "60601",
					fullAddress: "456 Oak St, Chicago, IL",
				},
				bedrooms: 2,
				bathrooms: 2,
				livingArea: 1200,
			},
		],
		activities: [],
		tags: [],
		followUpDate: "2023-09-15",
		lastContacted: "2023-09-11",
		metadata: {
			lastUpdate: "2023-09-11",
			address1: "456 Oak St, Chicago, IL",
		},
	},
	{
		id: uuid(),
		createdAt: "2023-09-09T09:00:00Z",
		updatedAt: "2023-09-09T10:00:00Z",
		firstName: "Alice",
		lastName: "Johnson",
		email: "testemail@gmail.com",
		phone: "(555) 345-6789",
		summary: "Looking to buy a 3-bedroom house.",
		status: "New Lead",
		source: "Cold Call",
		properties: [
			{
				id: uuid(),
				address: {
					street: "789 Maple Ave",
					city: "Austin",
					state: "TX",
					zipCode: "73301",
					fullAddress: "789 Maple Ave, Austin, TX",
				},
				bedrooms: 3,
				bathrooms: 2,
				livingArea: 1800,
			},
		],
		activities: [],
		tags: [],
		followUpDate: undefined,
		lastContacted: "2023-09-09",
		metadata: {
			lastUpdate: "2023-09-09",
			address1: "789 Maple Ave, Austin, TX",
		},
	},
	{
		id: uuid(),
		createdAt: "2023-09-08T09:00:00Z",
		updatedAt: "2023-09-08T10:00:00Z",
		firstName: "David",
		lastName: "Smith",
		email: "testemail@gmail.com",
		phone: "(555) 456-7890",
		summary: "Asked for more details about the 5-bedroom house.",
		status: "Closed Won",
		source: "Social Media",
		properties: [
			{
				id: uuid(),
				address: {
					street: "321 Birch St",
					city: "Seattle",
					state: "WA",
					zipCode: "98101",
					fullAddress: "321 Birch St, Seattle, WA",
				},
				bedrooms: 5,
				bathrooms: 4,
				livingArea: 4000,
			},
		],
		activities: [],
		tags: [],
		followUpDate: undefined,
		lastContacted: "2023-09-08",
		metadata: {
			lastUpdate: "2023-09-08",
			address1: "321 Birch St, Seattle, WA",
		},
	},
	{
		id: uuid(),
		createdAt: "2023-09-07T09:00:00Z",
		updatedAt: "2023-09-07T10:00:00Z",
		firstName: "Emma",
		lastName: "Wilson",
		email: "testemail@gmail.com",
		phone: "(555) 567-8901",
		summary: "Inquired about investment opportunities in the area.",
		status: "Closed Lost",
		source: "Email Campaign",
		properties: [
			{
				id: uuid(),
				address: {
					street: "654 Cedar Rd",
					city: "Denver",
					state: "CO",
					zipCode: "80201",
					fullAddress: "654 Cedar Rd, Denver, CO",
				},
				bedrooms: 2,
				bathrooms: 2,
				livingArea: 1500,
			},
		],
		activities: [],
		tags: [],
		followUpDate: "2023-09-20",
		lastContacted: "2023-09-07",
		metadata: {
			lastUpdate: "2023-09-07",
			address1: "654 Cedar Rd, Denver, CO",
		},
	},
	{
		id: uuid(),
		createdAt: "2023-09-06T09:00:00Z",
		updatedAt: "2023-09-06T10:00:00Z",
		firstName: "James",
		lastName: "Brown",
		email: "testemail@gmail.com",
		phone: "(555) 678-9012",
		summary: "Considering selling their 4-bedroom home.",
		status: "Contacted",
		source: "Direct Mail",
		properties: [
			{
				id: uuid(),
				address: {
					street: "987 Pine St",
					city: "Boston",
					state: "MA",
					zipCode: "02108",
					fullAddress: "987 Pine St, Boston, MA",
				},
				bedrooms: 4,
				bathrooms: 3,
				livingArea: 2500,
			},
		],
		activities: [],
		tags: [],
		followUpDate: "2023-09-18",
		lastContacted: "2023-09-06",
		metadata: {
			lastUpdate: "2023-09-06",
			address1: "987 Pine St, Boston, MA",
		},
	},
	{
		id: uuid(),
		createdAt: "2023-09-05T09:00:00Z",
		updatedAt: "2023-09-05T10:00:00Z",
		firstName: "Laura",
		lastName: "White",
		email: "testemail@gmail.com",
		phone: "(555) 789-0123",
		summary: "Looking for a vacation property.",
		status: "New Lead",
		source: "Website",
		properties: [
			{
				id: uuid(),
				address: {
					street: "543 Oakwood Ln",
					city: "Miami",
					state: "FL",
					zipCode: "33101",
					fullAddress: "543 Oakwood Ln, Miami, FL",
				},
				bedrooms: 3,
				bathrooms: 2,
				livingArea: 2000,
			},
		],
		activities: [],
		tags: [],
		followUpDate: "2023-09-22",
		lastContacted: "2023-09-05",
		metadata: {
			lastUpdate: "2023-09-05",
			address1: "543 Oakwood Ln, Miami, FL",
		},
	},
	{
		id: uuid(),
		createdAt: "2023-09-04T09:00:00Z",
		updatedAt: "2023-09-04T10:00:00Z",
		firstName: "Michael",
		lastName: "Lee",
		email: "testemail@gmail.com",
		phone: "(555) 890-1234",
		summary: "Interested in buying a multi-family unit.",
		status: "Closed Won",
		source: "Events",
		properties: [
			{
				id: uuid(),
				address: {
					street: "111 Redwood St",
					city: "San Francisco",
					state: "CA",
					zipCode: "94101",
					fullAddress: "111 Redwood St, San Francisco, CA",
				},
				bedrooms: 6,
				bathrooms: 5,
				livingArea: 5000,
			},
		],
		activities: [],
		tags: [],
		followUpDate: undefined,
		lastContacted: "2023-09-04",
		metadata: {
			lastUpdate: "2023-09-04",
			address1: "111 Redwood St, San Francisco, CA",
		},
	},
	{
		id: uuid(),
		createdAt: "2023-09-03T09:00:00Z",
		updatedAt: "2023-09-03T10:00:00Z",
		firstName: "Olivia",
		lastName: "Green",
		email: "testemail@gmail.com",
		phone: "(555) 901-2345",
		summary: "Looking for a property to rent out.",
		status: "Closed Lost",
		source: "Paid Ads",
		properties: [
			{
				id: uuid(),
				address: {
					street: "222 Walnut St",
					city: "Portland",
					state: "OR",
					zipCode: "97201",
					fullAddress: "222 Walnut St, Portland, OR",
				},
				bedrooms: 2,
				bathrooms: 1,
				livingArea: 1000,
			},
		],
		activities: [],
		tags: [],
		followUpDate: undefined,
		lastContacted: "2023-09-03",
		metadata: {
			lastUpdate: "2023-09-03",
			address1: "222 Walnut St, Portland, OR",
		},
	},
	{
		id: uuid(),
		createdAt: "2023-09-02T09:00:00Z",
		updatedAt: "2023-09-02T10:00:00Z",
		firstName: "Robert",
		lastName: "Taylor",
		email: "testemail@gmail.com",
		phone: "(555) 012-3456",
		summary: "Asked for information on 3-bedroom homes in the area.",
		status: "Contacted",
		source: "Other",
		properties: [
			{
				id: uuid(),
				address: {
					street: "333 Willow Ave",
					city: "New York",
					state: "NY",
					zipCode: "10001",
					fullAddress: "333 Willow Ave, New York, NY",
				},
				bedrooms: 3,
				bathrooms: 2,
				livingArea: 1900,
			},
		],
		activities: [],
		tags: [],
		followUpDate: "2023-09-19",
		lastContacted: "2023-09-02",
		metadata: {
			lastUpdate: "2023-09-02",
			address1: "333 Willow Ave, New York, NY",
		},
	},
];
