graph TD
  A[_docs]
  A1[_front_end_best_practices]
  A --> A1
  A1 --> B[_architecture]
  A1 --> C[_ci-cd]
  A1 --> D[_frameworks]
  A1 --> E[_languages]
  A1 --> F[_monitoring]
  A1 --> G[_monolithic_backend]
  A1 --> H[_security]
  A1 --> I[_system_design]
  A1 --> J[_testing]
  A1 --> K[_ui]
  A1 --> L[general.md]
  A1 --> M[suspense.md]

  %% Architecture
  B --> B1[mvc]
  B --> B2[mvp]
  B --> B3[mvvm]
  B --> B4[mvvm_c]
  B --> B5[viper]

  %% CI/CD
  C --> C1[_communication]
  C --> C2[_security]
  C --> C3[_testing]

  %% Frameworks
  D --> D1[_tools]
  D --> D2[next]
  D --> D3[react]

  %% Languages
  E --> E1[_data_validaiton]
  E --> E2[_linting]
  E --> E3[_package_managment]
  E --> E4[_state_managment]
  E --> E5[typescript]

  %% Monitoring
  F --> F1[_visualization]
  F --> F2[mixpanel]
  F --> F3[posthog]

  %% Monolithic Backend
  G --> G1[bun]
  G --> G2[deno]
  G --> G3[node]

  %% Security
  H --> H1[10_attacks.md]
  H --> H2[awesome.md]
  H --> H3[index.md]
  H --> H4[mdn.md]
  H --> H5[owasp_top_10.md]
  H --> H6[stanford.md]

  %% System Design
  I --> I1[patterns]

  %% Testing
  J --> J1[cucumber]
  J --> J2[playwright]

  %% UI
  K --> K1[_animations]
  K --> K2[_libraries]
  K --> K3[_styling]
  K --> K4[_three_dee]
  K --> K5[_ux]
  K --> K6[best_practices.md]
  K --> K7[concistency.md]
  K --> K8[dos_donts.md]
  K --> K9[principles.md]